#!/bin/sh

checkopt() {
	case "$1" in
		-h|-\?|--help)
			false;;
		-f|-t)        
			test x"${0##*/}" != x"scp";;
		*)
			true;;
	esac
}

if [ $# -gt 0 ] && checkopt "$1"; then
	if ! [ x"${SSH_AUTH_SOCK:+set}" = x"set" ]; then
		SSH_AUTH_SOCK=~/.ssh/@$(uname -n)
		if ! [ -e "$SSH_AUTH_SOCK" ]; then
			eval "$(umask 022; ssh-agent -a "$SSH_AUTH_SOCK")" || exit
		fi
		export SSH_AUTH_SOCK
	fi
	if [ x"${SSH_AUTH_SOCK:+set}" = x"set" ] && ! ssh-add -l >/dev/null 2>&1
	then
		({ command exec </dev/tty; } 2>/dev/null; ssh-add -t 1d) || exit
	fi
fi
exec "/usr/bin/${0##*/}" "$@"
