#!/bin/sh
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given.

if [ $# -eq 0 ]; then
    if [ -t 0 ]; then
	printf 'Usage:  %s filenames...\n' "${0##*/}" >&2
	exit 1
    fi
    set -- -
fi
if [ -t 1 ]; then
    exec vim -R -c 'let no_plugin_maps = 1' -c 'runtime! macros/less.vim' "$@"
else
    exec cat "$@"
fi
