#!/bin/sh
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given.

if [ $# -eq 0 ]; then
    if [ -t 0 ]; then
	printf 'Usage:  %s filenames...\n' "${0##*/}" >&2
	exit 1
    fi
    set -- -
fi
if [ -t 1 ]; then
    exec vim -R -c 'runtime macros/less.vim' +1 "$@"
else
    exec cat "$@"
fi
