#!/bin/sh
# Shell script to start Vim with less.vim.
# Read stdin if no arguments were given.

program=${0##*/}
if [ $# -eq 0 ]; then
    if [ -t 0 ]; then
	printf 'Usage:  %s filenames...\n' "$program" >&2
	exit 1
    fi
    set -- -
fi
case $program in
	*less) vim=${program%less} ;;
	*    ) vim=vim ;;
esac
if [ -t 1 ]; then
    exec $vim -R -c 'runtime macros/less.vim' +1 "$@"
else
    exec cat "$@"
fi
