#!/bin/sh

all=false
while [ x"$1" = x"-a" ]; do
	all=true
	shift
done
if [ x"$1" = x"--" ]; then
	shift
else
	case "$1" in
		-*) echo "$0: invalid option: $1" >&2; exit 2
	esac
fi

IFS=':'
found=true
for cmd
do
	foundsub=false
	for dir in $PATH
	do
		full="${dir:-.}/$cmd" 
		if [ -x "$full" ]; then
			foundsub=true
			echo "$full"
			$all || break
		fi
	done
	$foundsub || found=false
done

$found

# vim: ts=4 sw=2 sts=2
